Configure MongoDB
team-prstmw/HousesForSaleSearcherBE pull request #1
Opened 2022-02-16 18:19 UTC by mgoniszewska

2022-02-16 21:29 UTC, ike-tom commented on src/bootstrap.js
You can add 
const db = mongoose.connection;
db.on('error', (error) => console.error(error));

after function below(in line 18)

2022-02-16 21:30 UTC, ike-tom requested changes
I had to add NODE_ENV=development in the .env to make it work

2022-02-17 17:30 UTC, ike-tom approved these changes

2022-02-17 18:15 UTC, PatrykJurczyk approved these changes

2022-02-17 18:17 UTC, merged