Create new house endpoint
team-prstmw/HousesForSaleSearcherBE pull request #11
Opened 2022-02-24 01:41 UTC by shadowas-py

2022-02-25 20:37 UTC, FilipHalon commented on src/routes/createNewHouse.routes.js
> +import createNewHouseController from '../controllers/createNewHouse.controllers';
To keep the naming convention/routes storing practices similar to the rest of the code prepared so far, you could consider renaming the file to `houses.routes.js` and store here all house related routes.

2022-02-25 20:37 UTC, FilipHalon commented on src/models/createNewHouseModel.js
> +        houseId: {
I think houses will need a not nested `_id` to make them more easily referable for other schemas.

2022-02-25 20:37 UTC, FilipHalon commented on src/models/createNewHouseModel.js
> +            type: Date,
That could probably be also `default: Date.now(),`.

2022-02-26 22:47 UTC, FilipHalon requested changes

2022-02-26 22:47 UTC, FilipHalon commented on src/services/findAddress.js
> +export const findAddress = async (addressData) => {
It doesn't work exactly as expected. The error will be thrown if someone tries to save a new house with an address already in the database but if a not required part of the address is skipped next time, the house will be saved. Checking if a house hasn't been added would probably have to rely on a subset of address data consisting only required fields.

2022-02-26 22:47 UTC, FilipHalon commented on src/models/createNewHouseModel.js
> +    OtherFeatures:{
It would be more consistent if it was lowercased.

2022-02-26 22:47 UTC, FilipHalon commented on src/models/createNewHouseModel.js
> +    address:{
The address data could also use a street suffix and street number fields. It's best not to keep the data corresponding to the fields not as a part of any of the existing fields as parsing them could be difficult.

2022-02-27 07:39 UTC, FilipHalon commented on src/routes/createNewHouse.routes.js
> +      try {
Unfortunately, this `try-catch` block doesn't make much difference as if there is an error in `createNewHouseController` the route will return a response with the status 201 and an error message in its body.

2022-02-27 07:39 UTC, FilipHalon commented on src/models/createNewHouseModel.js
> +const housesSchema = new mongoose.Schema({
`houseSchema` will also need a status field which would store the information if a house was deleted, sold or is still active. You could assign the numbers 0, 1, 2 to the corresponding statuses and store them in the database.

2022-02-27 07:39 UTC, FilipHalon commented on src/models/createNewHouseModel.js
> +const housesSchema = new mongoose.Schema({
You could consider naming the fields in the schema the same as they are called on the front-end to make saving and retrieving data as effortless as possible unless you think some fields on the front-end should change their names. You might possibly also reconsider embeddings in this schema to make them work best with the most common operations like reading basic house data to be displayed on the houses list and on the map.

2022-02-27 16:55 UTC, mgoniszewska requested changes

2022-02-27 16:55 UTC, mgoniszewska commented on src/routes/createNewHouse.routes.js
> +          res.status(400).json({ message: err.message})
The rest of us use special packages that are inserting statuses while using more readable names for it.
`const { StatusCodes }= require( 'http-status-codes');`

2022-03-01 20:43 UTC, FilipHalon approved these changes
Please run `prettier` on all the files you changed.

2022-03-01 20:43 UTC, FilipHalon commented on src/services/findAddress.js
> +    if (address === null) return { status: 'success'};
Should it return anything? In the controller the result of this function isn't assigned to any variable.

2022-03-02 18:55 UTC, merged