add house deletion endpoint
team-prstmw/HousesForSaleSearcherBE pull request #18
Opened 2022-03-04 21:45 UTC by ike-tom

2022-03-06 12:55 UTC, mgoniszewska requested changes

2022-03-06 12:55 UTC, mgoniszewska commented on src/controllers/house.controllers.js
> +};
The favorite model should be only used by the favorite controller and then if you want to use it you should import the necessary function from the favorite controller.

2022-03-06 12:55 UTC, mgoniszewska commented on src/controllers/house.controllers.js
> +};
You can use `findByIdAndUpdate()` function.
I think that this task needs the house's status changed and not only removed from favorites.

2022-03-06 17:04 UTC, FilipHalon requested changes

2022-03-06 17:04 UTC, FilipHalon commented on src/routes/houses.routes.js
> +  router.delete('/houses/:houseId', async (req, res) => {
Isn't this endpoint currently returning a single favorite instance?

2022-03-09 09:44 UTC, mgoniszewska approved these changes

2022-03-09 15:33 UTC, FilipHalon commented on src/routes/houses.routes.js
> +  });
There's no response.

2022-03-13 12:11 UTC, FilipHalon approved these changes

2022-03-13 12:11 UTC, FilipHalon commented on src/controllers/house.controllers.js
> +    { houseStatus: 0 }
Please use here the corresponding constant.

2022-03-13 17:00 UTC, merged